#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set $GRAALVM_HOME"
    exit 1
fi

mkdir -p classes
clojure -e "(compile 'puget-cli.main)"

"$GRAALVM_HOME/bin/gu" install native-image

"$GRAALVM_HOME/bin/native-image" \
    -cp "$(clojure -Spath):classes" \
    -H:Name=puget \
    -H:+ReportExceptionStackTraces \
    --initialize-at-build-time  \
    "-J-Dclojure.spec.skip-macros=true" \
    "-J-Dclojure.compiler.direct-linking=true" \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g" \
    puget_cli.main
